### ISSUE TITLE
get this error when try python manage.py migrate

### ISSUE THREAD

**Issue by mvmthecreator** [emencia/emencia-django-socialaggregator#4]
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'socialaggregator.FeedPlugin'>]

**Comment by rage2000** [comment]
Can you add more context ? (explicit traceback and explain the context (django version ?), is it a project that you build from scratch or a migration from older version ?)

**Comment by mvmthecreator** [comment]
hi, thanks for fast replay.

I have a running django-cms installation and try to integrate a new installation of social-aggregator.

i use django 1.7

     Applying filebrowser.0001_initial...Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
        executor.migrate(targets, plan, fake=options.get("fake", False))
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
            self.apply_migration(migration, fake=fake)
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
        if self.detect_soft_applied(migration):
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
        apps = project_state.render()
      File "/home/user/DevWorkspace/PythonProjects/AllesAusprobieren/djangocms_stable/venv/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
        "for more" % new_unrendered_models
    django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'socialaggregator.FeedPlugin'>]
    This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
     in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

**Comment by rage2000** [comment]
I think the problem is django1.7 (we still don't use it in production) and the new migrate system.

I will try to see it during the next week but if your have some time i think that the solution is to use the SOUTH_MIGRATION_MODULES settings ( http://south.readthedocs.org/en/latest/settings.html#south-migration-modules ) and specify emencia-django-socialaggregator into it

**Comment by mvmthecreator** [comment]
thanks for your fast reply. I think i will try to switch to 1.8. Its the next Long Term Support Version.

**Comment by rage2000** [comment]
I think the problem will be the same with 1.8

**Comment by mvmthecreator** [comment]
i will try and then reply to you.

**Comment by rage2000** [comment]
Sorry for take some time but i tried to install eds on django1.8 and django1.7 fresh install and no problem on these two on "python manage.py migrate" (the south migration scripts of eds are simply not used)

# python manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: filebrowser, socialaggregator
  Apply all migrations: admin, contenttypes, taggit, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table socialaggregator_feed
    Creating table socialaggregator_aggregator_feeds
    Creating table socialaggregator_aggregator
    Creating table socialaggregator_ressource_feeds
    Creating table socialaggregator_ressource
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK

# python manage.py migrate --list
admin
 [X] 0001_initial
auth
 [X] 0001_initial
contenttypes
 [X] 0001_initial
sessions
 [X] 0001_initial
socialaggregator
 (no migrations)
taggit
 [X] 0001_initial
 [X] 0002_auto_20150616_2121

After that I read again your log and I observed that is not eds bugging on migrate script but filebrowser.
